experiment_name: "Gen6.2"
device: "dml"
output_dir: "checkpoints/Gen6.2"

data:
  dataset_path: "datasets/Gen6.1/"
  batch_size: 16
  num_workers: 4

model:
  input_dim: 2048
  output_dim: 4096
  hidden_dim: 1024

training:
  epochs: 5        # Mude de 100 para 2 (sÃ³ para testar o loop)
  learning_rate: 0.0001
  save_every: 1    # Mude de 5 para 1 (para garantir que salve o .pth logo)

loss:
  temperature: 0.1
  lambda_mse: 0.1
